name = "QuantumESPRESSOCli"
uuid = "f713baf6-9299-4878-8719-8ad597e49a7b"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
AbInitioSoftwareBase = "df5135bc-470e-46c6-b451-292e27ca5b84"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"

[compat]
Comonicon = "0.5 - 0.10, 0.11"
Configurations = "0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
